module.exports = {
  configs: {
    starter: {
      plugins: ['fp', 'smells', 'import'],
      extends: [
        'plugin:prettier/recommended',
        'plugin:lodash/recommended',
        'plugin:fp/recommended',
        'plugin:lodash-fp/recommended',
        'plugin:import/errors',
      ],
      rules: {
        quotes: ['error', 'single'],
        semi: ['error', 'never'],
        indent: 'off',
        radix: ['error', 'always'],
        'no-console': process.env.NODE_ENV === 'production' ? 'off' : 'off',
        'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
        'arrow-parens': 'off',
        'generator-star-spacing': 'off',
        'class-methods-use-this': 'error',
        'comma-dangle': ['warn', 'always-multiline'],
        'consistent-return': ['error', { treatUndefinedAsUnspecified: true }],
        'prefer-destructuring': [
          'warn',
          {
            VariableDeclarator: {
              array: false,
              object: true,
            },
            AssignmentExpression: {
              array: false,
              object: true,
            },
          },
          {
            enforceForRenamedProperties: true,
          },
        ],
      },
      'no-bitwise': 'error',
      'no-else-return': 'error',
      'no-empty-pattern': 'off',
      'no-extra-bind': 'error',
      'no-extra-boolean-cast': 'error',
      'no-invalid-this': 'error',
      'no-lonely-if': 'error',
      'no-negated-in-lhs': 'error',
      'no-new-wrappers': 'error',
      'no-obj-calls': 'error',
      'no-undef': 'error',
      'no-unneeded-ternary': 'error',
      'no-useless-call': 'error',
      'no-useless-return': 'error',
      'no-var': 'error',
      'import/no-unresolved': 'off',
      'func-style': ['error', 'expression'],
      'space-before-function-paren': 'off',
      'smells/no-switch': 'error',
      'smells/no-complex-switch-case': 'error',
      'smells/no-setinterval': 'error',
      'smells/no-this-assign': 'error',
      'lodash/import-scope': ['warn', 'full'],
      'lodash/prefer-lodash-method': [2, { ignoreObjects: ['L', 'router'] }],
      'lodash-fp/use-fp': 'warn',
      'lodash-fp/consistent-name': ['warn', 'L'],
      'fp/no-nil': 'off',
      'fp/no-this': 'off',
      'fp/no-unused-expression': 'off',
      'fp/no-mutation': [
        'error',
        {
          commonjs: true,
          allowThis: true,
          exceptions: [{ object: 'state' }, { object: 'element' }],
        },
      ],
    },
  },
}
